


CITIES = {
    "Таллинн": "Tallinn",
    "Маарду": "Maardu",
    "Кейла": "Keila",
    "Палдиски": "Paldiski",
    "Локса": "Loksa",
    "Тарту": "Tartu",
    "Элва": "Elva",
    "Калласте": "Kallaste",
    "Нарва": "Narva",
    "Силламяэ": "Sillamae",
    "Йыхви": "Johvi",
    "Пярну": "Parnu",
    "Килинги-Нымме": "Kilingi-Nomme",
    "Кохтла-Ярве": "Kohtla-Jarve",
    "Вильянди": "Viljandi",
    "Раквере": "Rakvere",
    "Кунда": "Kunda",
    "Тапа": "Tapa",
    "Хаапсалу": "Haapsalu",
    "Кярдла": "Kardla",
    "Курессааре": "Kuressaare",
    "Пайде": "Paide",
    "Тюри": "Turi",
    "Рапла": "Rapla",
    "Йыгева": "Jogeva",
    "Муствеэ": "Mustvee",
    "Пылва": "Polva",
    "Выру": "Voru",
    "Ряпина": "Rapina",
    "Валга": "Valga",
    "Тырва": "Torva",
    "Отепя": "Otepaa",
}
